spring:
  datasource:
    driver_class_name: oracle.jdbc.OracleDriver
    password: PeterSong123
    url: jdbc:oracle:thin:@petertestdb_medium?TNS_ADMIN=/Users/psong/Downloads/Wallet_petertestDB
    username: TODOUSER
jpa:
  database: ORACLE
  database-platform: org.hibernate.dialect.Oracle10gDialect
  hibernate:
    ddl-auto: none
  show-sql: true
